# Generated by Django 3.0.6 on 2020-06-02 12:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rentalpropertyapp', '0002_rentingitem_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentingitem',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
